using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace TMS.Models
{
    public class TMSContext : DbContext
    {
        // You can add custom code to this file. Changes will not be overwritten.
        // 
        // If you want Entity Framework to drop and regenerate your database
        // automatically whenever you change your model schema, add the following
        // code to the Application_Start method in your Global.asax file.
        // Note: this will destroy and re-create your database with every model change.
        // 
        // System.Data.Entity.Database.SetInitializer(new System.Data.Entity.DropCreateDatabaseIfModelChanges<TMS.Models.TMSContext>());

        //Added for customized connection string "TMSContext"
        public TMSContext()
            : base("TMSContext")
        {
        }

        public DbSet<UserProfile> UserProfiles { get; set; } //Added DbSet<UserProfile>

        public DbSet<TMS.Models.Trainer> Trainers { get; set; } //Auto generated by scaffolding

        public DbSet<TMS.Models.Training> Trainings { get; set; } //Auto generated by scaffolding
    }
}