// This file was auto-generated by ML.NET Model Builder. 

using System;
using SentimentAnalysisML.Model;

namespace SentimentAnalysisML.ConsoleApp
{
    class Program
    {
        static void Main(string[] args)
        {
            // Create single instance of sample data from first line of dataset for model input
            ModelInput sampleData = new ModelInput()
            {
                Col0 = @"The food of Hotel Sonargaon was awesome",
            };

            // Make a single prediction on the sample data and print results
            var predictionResult = ConsumeModel.Predict(sampleData);

            Console.WriteLine("Using model to make single prediction -- Comparing actual Col1 with predicted Col1 from sample data...\n\n");
            Console.WriteLine($"Col0: {sampleData.Col0}");
            Console.WriteLine($"\n\nPredicted Col1 value {predictionResult.Prediction} \nPredicted Col1 scores: [{String.Join(",", predictionResult.Score)}]\n");

            //If result is 1 means positive otherwise negative
            string sentiment = predictionResult.Prediction == "1" ? "Positive" : "Negative";
            Console.WriteLine($"Sentiment: {sentiment} \n");

            Console.WriteLine("=============== End of process, hit any key to finish ===============");
            Console.ReadKey();
        }
    }
}
